version: '3'

services:
  php:
    build: ./docker/php
    volumes:
      - .:/var/www/html

  mysql:
    build: ./docker/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mlrtpd
      MYSQL_DATABASE: sample
      MYSQL_USER: app
      MYSQL_PASSWORD: mlrtpd
      TZ: Asia/Tokyo
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./database:/home/database
